### ISSUE TITLE
Support non-latest npm dist tags

### ISSUE THREAD

**Issue by noahnu** [tophat/monodeploy#223]
**Is your feature request related to a problem? Please describe.**

Currently we publish with tag=latest, are there use cases where we want to specify some other tag? Pre-release?

**Describe the solution you'd like**

Unclear.

**Comment by noahnu** [comment]
Is this required outside of pre-release? (@fmal thoughts?)

**Comment by fmal** [comment]
@noahnu personally i can't think of any common use case other than prereleases (via `alpha`, `beta`, `next`, `rc` tags and so on), maybe something like `experimental` where you could test experimental stuff that doesn't even get merged with the `latest` but i haven't had a need for anything like that

**Comment by noahnu** [comment]
Will close this out then. We can always re-open it.

**Comment by etimberg** [comment]
An interesting thought on this topic. I've used `next` as the dist tag for alpha and beta releases in libraries that I maintain.

One thing that might be nice would be a way to remove these tags when `latest` is published (or publish both `latest` and `next` at the same time). NPM sadly doesn't do this by default, so if you start with `latest` pointing to `v2.5.0` and `next` pointing to `v2.6.0-rc.1`, when you publish `v2.6.0` as `latest`, `next` will be incorrect until another pre-release is published.

**Comment by noahnu** [comment]
I wonder if deleting the "next" tag might create confusion -- or have any other unintended consequences.

Keeping the pre-release tag in sync with next is an interesting idea.
