### ISSUE TITLE
Support generating individual changelog files per workspace

### ISSUE THREAD

**Issue by noahnu** [tophat/monodeploy#285]
**Is your feature request related to a problem? Please describe.**

Currently we generate one combined changelog file in the project root. Some projects in the wild use individual changelogs per package of the monorepo. We should support this.

**Describe the solution you'd like**

A flag to make the changelog path relative to the workspace cwd.

**Comment by noahnu** [comment]
Options:

- Add a `changelogPerPackage: boolean` config option
- Use a token in the `changelogFilename` such as `<packageDir>` that would be replaced by a per package cwd. If we see this token, we assume changelogPerPackage. Has the benefit of one less config option.

**Comment by mcataford** [comment]
I love the idea, I think it can be really useful, especially if the monorepo being monodeployed has a lot of packages. In those cases, a combined changelog might be far too heavy to really be useful. :thinking: 

Of the two options, I personally fancy the second one the most. It has the benefit of opening the door to deeper customization (i.e. it would allow something like `<packageDir>/artifacts/` if we want the changelogs to be generated in a subfolder of the package, or even further, if we wanted it to be per-package, but centrally located, perhaps something like `changelogs/<packageName>.md` would be possible [if we allowed a token that represents the package name, that is). If we wanted to support the example use cases above with the CLI flag, we'd have to add the tokens anyway, which would essentially circle back to Option 2, but with a CLI flag on top. :shrug:
