### ISSUE TITLE
support `conventionalChangelogConfig` returning factory function

### ISSUE THREAD

**Issue by fmal** [tophat/monodeploy#388]
I would like to use [conventional-changelog-conventionalcommits](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-conventionalcommits) as `conventionalChangelogConfig`. The problem is that this config is returning a factory function that returns a promise rather than promise. My current workaround is to create a custom wrapper that exports the config:

```js
const config = require('conventional-changelog-conventionalcommits');

module.exports = config();
```

and reference it like this in `monodeploy.config.js`:

```js
const monodeployConfig = {
  conventionalChangelogConfig: path.resolve(
    path.join(__dirname, 'conventional-changelog.config.js'),
  )
}
```

I wonder if `monodeploy` could support configs returning factory function, something like this:

```js
  const conventionalConfigModule = require(require.resolve(
      config.conventionalChangelogConfig,
      { paths: [config.cwd] },
  ))
  const conventionalConfig = await (typeof conventionalConfigModule ===
  'function'
      ? conventionalConfigModule()
      : conventionalConfigModule)
```

in https://github.com/tophat/monodeploy/blob/master/packages/changelog/src/changelog.ts#L41

the downside is that there would be no way to pass configuration to the config factory function, so maybe the wrapper approach is the way to go?

**Comment by noahnu** [comment]
100% we can do this. Would you be interested in opening a PR? Otherwise I'll get to it in the next 2 hours.

**Comment by noahnu** [comment]
How does lerna handle the parameters to that conventional changelog config?

**Comment by fmal** [comment]
@noahnu lerna supports specifying preset configurations via object where you provide the name of the package and any other additional properties:
```json
{
  "changelogPreset": {
    "name": "conventionalcommits",
    "issueUrlFormat": "{{host}}/{{owner}}/{{repository}}/issues/{{id}}"
  }
}
```

https://github.com/lerna/lerna/blob/6cb8ab2d4af7ce25c812e8fb05cd04650105705f/core/conventional-commits/lib/get-changelog-config.js#L43

i think this is a reasonable approach, but in my case i just wanted the configuration to work without any additional configuration and this will work perfectly, thank you 👍

**Comment by noahnu** [comment]
This would be useful to add. I want to add arbitrary configuration for plugins as well, so I'll take a look at this over the weekend (hopefully).

**Comment by fmal** [comment]
@noahnu was going to add a PR for that and extracted the following util:

```ts
import type { MonodeployConfiguration } from '@monodeploy/types'

type ConventionalStrategy = { level?: number | null }

type ConventionalChangelogConfig = {
    parserOpts: conventionalCommitsParser.Options
    recommendedBumpOpts: {
        whatBump: (
            commits: conventionalCommitsParser.Commit[],
        ) => ConventionalStrategy
    }
}

export const resolveConventionalConfig = async (
    config: MonodeployConfiguration,
): Promise<ConventionalChangelogConfig> => {
    if (!config.conventionalChangelogConfig) {
        throw new Error('No conventional changelog config provided')
    }

    const conventionalConfigName =
        typeof config.conventionalChangelogConfig === 'string'
            ? config.conventionalChangelogConfig
            : config.conventionalChangelogConfig.name
    const conventionalConfigConfig =
        typeof config.conventionalChangelogConfig === 'object'
            ? config.conventionalChangelogConfig
            : {}
    // ghost-imports-ignore-next-line
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const conventionalConfigModule = require(require.resolve(
        conventionalConfigName,
        { paths: [config.cwd] },
    ))

    return await (typeof conventionalConfigModule === 'function'
        ? conventionalConfigModule(conventionalConfigConfig)
        : conventionalConfigModule)
}
```

which you can then use like this:

```ts
const conventionalConfig = await resolveConventionalConfig(config)
```

in `changelog.ts` and `versionStrategy.ts`

also adjusted the `conventionalChangelogConfig` type to be:

```
  conventionalChangelogConfig?:
      | string
      | {
            name: string
            [key: string]: unknown
        }
```

Don't know what would be the best place to put this util though. There is no `packages/common` or `packages/utils` for shared utils like this and i guess it doesn't fit into `packages/io` 👍  any recommendations where to place it would be helpful or you can just take it from there if you wish.
