### ISSUE TITLE
`dry-mode` modifies versions in `package.json` files

### ISSUE THREAD

**Issue by fmal** [tophat/monodeploy#390]
I have noticed that running monodeploy with the `--dry-mode` flag results in versions being bumped in `package.json` files. I guess in dry mode any modifications should be skipped (by returning early before calling`patchPackageJsons`) ?

**Comment by noahnu** [comment]
I like the idea of being able to see what the modification would be. Perhaps we do the package.json modification in memory and print it out with a trace log level.

I'm going to revisit the logging later. In the meantime, let's just skip saving the package json. I'll put up a PR in the next 2 hours.

**Comment by noahnu** [comment]
Should we be executing lifecycle scripts in dry run mode?

**Comment by fmal** [comment]
@noahnu oh i haven't even considered lifecycle scripts, it's great that you were able to address this properly! 👍
