### ISSUE TITLE
Minimum version of git (2.13) is required for last tag detection

### ISSUE THREAD

**Issue by noahnu** [tophat/monodeploy#411]
**Describe the bug**

git 2.13 is required for last tag detection because of the `--exclude` argument of `git describe`. This is not documented anywhere and is an unexpected breaking change after prerelease support was added.

**Expected behavior**

Git 2.13 should be supported, and we should be testing with a minimum git version.

**Comment by noahnu** [comment]
We should check the git version at the beginning of the publish pipeline.

**Comment by shawndrape** [comment]
@noahnu After a loooong hiatus (and noticing that the initial chore got closed) I'm looking at coming back to this. However, it's unclear if this is worth doing still, with 2.41 being the latest version and 2.13 being from 2017. Should it just get closed out?

**Comment by noahnu** [comment]
I think we can probably add a note somewhere in the docs (Gatsby site) about system requirements but otherwise don't need to enforce anything. There's a chance there's already a note in the docs (would have to do a search to double check).
