### ISSUE TITLE
[plugin-github] Create release even when there's no changelog

### ISSUE THREAD

**Issue by gabormagyar** [tophat/monodeploy#501]
**Is your feature request related to a problem? Please describe.**

Problem: Packages in a monorepo can get a version bump and a release because their dependencies were updated, but in this case they get no changelog.

GitHub release plugin then says:
> [GitHub Plugin] Skipping release for package as there's no changelog.

**Describe the solution you'd like**

I would like the plugin to create an empty release, or maybe even a release with "no changelog" or "dependencies updated" or something similar, but certainly not to swallow the fact that a release happened.

**Describe alternatives you've considered**

Perhaps hide this behind a config flag if this isn't a default desired behavior.

**Comment by noahnu** [comment]
Released in https://github.com/tophat/monodeploy/releases/tag/%40monodeploy%2Fplugin-github%400.5.0

See docs: https://tophat.github.io/monodeploy/plugins#github
