### ISSUE TITLE
Changelog links are broken on GitLab (and possibly other platforms)

### ISSUE THREAD

**Issue by Papooch** [tophat/monodeploy#782]
**Is your feature request related to a problem? Please describe.**

Currently, the generated markdown changelog looks like this in case the group strucure is nested more than 2. The package name is completely omitted. Additionally, I have the feeling that the link format would still need to be changed :thinking: 

```md
## [1.2.0](https://gitlab.selfhosted.com/root-group/group/compare/@scope/package@1.1.0...@scope/package@1.2.0) "@scope/package" (2023-07-20)<a name="1.2.0"></a>

### Features

* test commit ([9b8ec82](https://gitlab.selfhosted.com/root-group/group/commits/9b8ec82))

```
Do we currently have any control over this?

**Describe the solution you'd like**

I would like to be able to supply a template file from which the changelog is generated (handlebars, ejs, ..).
Also, I would like to receive the _raw_ values in _plugins_, since currently only the generated markdown is passed as a string which makes it hard to work with.

**Describe alternatives you've considered**

Running custom transformations on the generated markdown, but it's not ideal at all.

**Additional context**

(I'm considering submitting a webhook notification plugin, but not being able to access the raw changelog values is a big hurdle. Also since we're using GitLab, the changelog links do not work.

EDIT: the missing url path segment seems to be caused by a bug in `parseRepositoryProperty` from `@monodeploy/git`, but I'm not sure how to approach the different link formats. It also seems that no link to a merge request is generated for GL.

**Comment by noahnu** [comment]
The changelogs are generated via the conventional changelog project. If you don't specify a custom changelog config, we have a basic "default" one.

This is the one we use in our other projects: https://github.com/tophat/commit-utils/tree/main/packages/conventional-changelog-config

You can also use any of the open source configs here: https://github.com/conventional-changelog/conventional-changelog

**Comment by Papooch** [comment]
Thank you, that makes sense. But how do I know which one to use? It's a bit overwhelming to me and I don't understand where to look? How do I find the package that I need to use instead of `@tophat/conventional-changelog-config`?

**Comment by Papooch** [comment]
So actually, with the fix, the links now work correctly on GitLab, too.
