### ISSUE TITLE
Base version

### ISSUE THREAD

**Issue by akospaska** [tophat/monodeploy#923]
Hello Guys,

I have read the documentation but I couldn't find how the monodeploy finds out what is the base version what should be upgraded?

I have seen in the sourceCode we fetch the packages tags from the package registry, so that could be a good start.
https://github.com/tophat/monodeploy/blob/main/packages/node/src/index.ts#L118

But do we fetch the repository tags too?

**Comment by noahnu** [comment]
https://github.com/monoweave/monoweave
